visualization:
  activate: True
  format: "pointcloud" # image will come later
  num_samples_per_epoch: -1 # -1: visualization all
  deterministic: True # False -> Randomly sample elements from epoch to epoch
  vis_data: [] #["test"]  #visualize test when run eval.py
  saved_keys: 
    pos: [['x', 'float'], ['y', 'float'], ['z', 'float']]
    y: [['l', 'float']]
    pred: [['p', 'float']]