defaults: # for loading the default config
  - task: segmentation # Task performed (segmentation, classification etc...)
    optional: True
# Type of model name (conf/models/segmentation/*.yaml )to use
# pointnet, pointnet2, kpconv
  - model_type: pointnet2
    optional: True
  - dataset: urbanmeshused #s3disfused
    optional: True

  - visualization: default #yaml file name
  - lr_scheduler: exponential
# Types of training hyperparamters (conf/training/*.yaml ) default,
# PointNet, PointNet++: default; KPConv: kpconv;
  - training: default

  - debugging: default.yaml
  - models: ${defaults.0.task}/${defaults.1.model_type}
  - data: ${defaults.0.task}/${defaults.2.dataset}
  - sota # Contains current SOTA results on different datasets (extracted from papers !).
  - hydra/job_logging: custom
  - hydra/output: custom  # add the support for user-defined experiment folder (where to save the experiment files)

job_name: benchmark # prefix name for saving the experiment file.

# models in conf/models/segmentation/*.yaml:
# PointNet: PointNet; PointNet++: pointnet2_charlesmsg, pointnet2_largemsg; KPConv: KPConvPaper;
model_name: pointnet2_largemsg # Name of the specific model to load

update_lr_scheduler_on: "on_epoch" # ["on_epoch", "on_num_batch", "on_num_sample"]
selection_stage: ""
pretty_print: False
eval_frequency: 1

tracker_options: # Extra options for the tracker
  full_res: False
  make_submission: False
  track_boxes: False
